version: 0.2

phases:
  pre_build:
    commands:
      - echo Pull grafana/k6 image..
      - docker pull grafana/k6
  build:
    commands:
      - echo Run performance test
      - docker run -i grafana/k6 run - <scripts/test.js
  post_build:
    commands:
      - echo Performance test complete
